version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: dev
    restart: always
    command: npx next dev
    environment:
      - NODE_ENV=development
      - "NEXT_WEBPACK_USEPOLLING=1"
    volumes:
      - ./frontend:/web
      - /web/node_modules
      - /web/.next
    ports:
      - "30001:3000"

  dema-cms:
    container_name: dema-cms
    build: ./dema-cms
    image: dema-cms:latest
    restart: unless-stopped
    env_file: ./dema-cms/.env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: dema-cmsDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./dema-cms/config:/opt/app/config
      - ./dema-cms/src:/opt/app/src
      - ./dema-cms/package.json:/opt/package.json
      - ./dema-cms/package-lock.json:/opt/package-lock.json

      - ./dema-cms/.env:/opt/app/.env
      - ./dema-cms/public/uploads:/opt/app/public/uploads
    ports:
      - '30002:1337'
    networks:
      - dema-cms
    depends_on:
      - dema-cmsDB
      
  dema-cmsDB:
    container_name: dema-cmsDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: ./dema-cms/.env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - dema-cms-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - '5432:5432'
    networks:
      - dema-cms
      
  dema-cmsAdminer:
    container_name: dema-cmsAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=dema-cmsDB
    networks:
      - dema-cms
    depends_on:
      - dema-cmsDB

volumes:
  dema-cms-data:

networks:
  dema-cms:
    name: Dema-cms
    driver: bridge